import { StyleSheet } from "react-native";

import { colors } from "../../constants/theme";

export const editorStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 12,
  },
  header: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: colors.surfaceSoft,
  },
  nextButton: {
    minWidth: 66,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
  },
  nextText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  previewCard: {
    position: "relative",
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: colors.surfaceSoft,
    marginTop: 12,
  },
  verticalPreviewCard: {
    alignSelf: "center",
  },
  previewMedia: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  previewPoster: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  emptyPreview: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 12,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
    textAlign: "center",
  },
  filterTint: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
  },
  previewEffectLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
  },
  overlayText: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.52)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  draggableTextBox: {
    position: "absolute",
    zIndex: 5,
    maxWidth: "78%",
    borderRadius: 6,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  timeline: {
    marginTop: 12,
    gap: 7,
  },
  timelineTimeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  timelineEditor: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  timelineSideButton: {
    width: 28,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  clipStack: {
    flex: 1,
    minHeight: 92,
    justifyContent: "center",
  },
  previewPlayButton: {
    position: "absolute",
    zIndex: 6,
    right: 14,
    bottom: 14,
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: colors.primary,
  },
  timelineTrack: {
    height: 42,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 5,
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  timelineFrame: {
    flex: 1,
    minWidth: 28,
    height: 48,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.22)",
    backgroundColor: "#2F3437",
  },
  timelineFrameActive: {
    backgroundColor: colors.primary,
  },
  frameShade: {
    flex: 1,
    margin: 2,
    borderRadius: 3,
    backgroundColor: "rgba(245,239,235,0.16)",
  },
  clipTrack: {
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.surface,
    backgroundColor: "#1F2325",
  },
  trimHandle: {
    width: 28,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
  },
  addClipButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.surface,
    marginHorizontal: 5,
  },
  audioTrack: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#DCE8F0",
    marginTop: 6,
    paddingHorizontal: 9,
  },
  audioTrackText: {
    maxWidth: 72,
    color: colors.primary,
    fontSize: 11,
    fontWeight: "800",
    marginHorizontal: 5,
  },
  waveMiniRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  waveMiniBar: {
    width: 8,
    borderRadius: 8,
    backgroundColor: colors.secondary,
  },
  playhead: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "46%",
    width: 2,
    backgroundColor: colors.text,
  },
  splitPlayhead: {
    backgroundColor: colors.primary,
  },
  playheadCap: {
    position: "absolute",
    top: -4,
    left: -4,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.text,
  },
  timelineMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  metaText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  panel: {
    minHeight: 104,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: 12,
    paddingTop: 10,
  },
  toolRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
    marginTop: 10,
  },
  toolButton: {
    flex: 1,
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 4,
  },
  toolButtonActive: {
    backgroundColor: colors.primary,
  },
  toolLabel: {
    color: colors.text,
    fontSize: 10,
    fontWeight: "800",
    marginTop: 5,
  },
  toolLabelActive: {
    color: colors.onPrimary,
  },
  sliderLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 2,
  },
  sliderHintRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: -4,
    paddingHorizontal: 3,
  },
  textInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    color: colors.text,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
  },
  textPanel: {
    gap: 8,
  },
  textOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  textOptionButton: {
    minWidth: 38,
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 9,
  },
  textOptionButtonActive: {
    backgroundColor: colors.primary,
  },
  textOptionText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  textOptionTextActive: {
    color: colors.onPrimary,
  },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  colorSwatchActive: {
    borderColor: colors.primary,
  },
  saturationBlock: {
    flex: 1,
  },
  saturationSliderWrap: {
    position: "relative",
    justifyContent: "center",
    marginTop: -2,
  },
  saturationRail: {
    position: "absolute",
    left: 15,
    right: 15,
    top: 18,
    height: 6,
    flexDirection: "row",
    overflow: "hidden",
    borderRadius: 6,
  },
  videoErrorBadge: {
    position: "absolute",
    zIndex: 7,
    left: 10,
    right: 10,
    top: 10,
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 8,
    backgroundColor: "rgba(47,65,86,0.88)",
    paddingHorizontal: 10,
  },
  trimPanel: {
    gap: 4,
  },
  trimHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  trimVisualTrack: {
    position: "relative",
    height: 42,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#2F3437",
    marginVertical: 4,
  },
  trimSelectedArea: {
    position: "absolute",
    top: 0,
    bottom: 0,
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderColor: colors.primary,
    backgroundColor: "rgba(86,124,141,0.28)",
  },
  trimDimArea: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(31,29,28,0.68)",
  },
  trimEdgeHandle: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 4,
    borderRadius: 4,
    backgroundColor: colors.onPrimary,
  },
  videoErrorText: {
    color: colors.onPrimary,
    fontSize: 11,
    fontWeight: "800",
  },
  audioPlayButton: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 36,
    backgroundColor: colors.primary,
    marginBottom: 26,
  },
  editorWaveform: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  editorWaveBar: {
    width: 5,
    borderRadius: 4,
  },
});
