import { StyleSheet } from "react-native";

import { colors } from "../../constants/theme";

export const editorStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  header: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: colors.surfaceSoft,
  },
  nextButton: {
    minWidth: 66,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
  },
  nextText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  previewCard: {
    minHeight: 360,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: colors.surfaceSoft,
    marginTop: 18,
  },
  previewMedia: {
    width: "100%",
    height: "100%",
  },
  emptyPreview: {
    flex: 1,
    minHeight: 360,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 12,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
    textAlign: "center",
  },
  filterTint: {
    ...StyleSheet.absoluteFillObject,
  },
  overlayText: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 24,
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.52)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  timeline: {
    marginTop: 18,
    gap: 10,
  },
  timelineTrack: {
    height: 58,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 5,
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  timelineFrame: {
    flex: 1,
    borderRadius: 4,
    backgroundColor: colors.tertiary,
  },
  timelineMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  metaText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  panel: {
    minHeight: 124,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: 18,
    paddingTop: 14,
  },
  toolRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
    marginTop: 14,
  },
  toolButton: {
    flex: 1,
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 4,
  },
  toolButtonActive: {
    backgroundColor: colors.primary,
  },
  toolLabel: {
    color: colors.text,
    fontSize: 10,
    fontWeight: "800",
    marginTop: 5,
  },
  toolLabelActive: {
    color: colors.onPrimary,
  },
  sliderLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
  },
  stickerRow: {
    gap: 10,
    paddingVertical: 4,
  },
  stickerOption: {
    width: 76,
    minHeight: 82,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    padding: 8,
  },
  stickerOptionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.tertiary,
  },
  stickerOptionImage: {
    width: 52,
    height: 42,
    marginBottom: 6,
  },
  stickerOptionText: {
    color: colors.text,
    fontSize: 10,
    fontWeight: "800",
  },
  stickerOptionTextActive: {
    color: colors.primary,
  },
  textInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    color: colors.text,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
  },
  audioPlayButton: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 36,
    backgroundColor: colors.primary,
    marginBottom: 26,
  },
  editorWaveform: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  editorWaveBar: {
    width: 5,
    borderRadius: 4,
  },
});
